# Generated by Django 5.0.6 on 2024-05-24 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1)),
                ('anno', models.CharField(max_length=1)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facultad')),
            ],
        ),
    ]
